### ISSUE TITLE
Latest release appears "unsigned"

### ISSUE THREAD

**Issue by ag14spirit** [tailscale/tailscale-qpkg#103] opened 2023-06-18 22:32 UTC
QTS 5.1.0.2418 (build 2023-06-03) on QNAP TS-932PX

**Comment by DentonGentry** [comment] 2023-06-18 23:45
Duplicate of https://github.com/tailscale/tailscale-qpkg/issues/99. We expect to correct this in the 1.42 release.

**Closed by DentonGentry** 2023-06-18 23:45 UTC

**Comment by ag14spirit** [comment] 2023-06-19 00:19
I'm so sorry 🤦🏼‍♂️

I swear I checked...but clearly not very well.

**Comment by marcozink** [comment] 2023-06-19 20:52
> Duplicate of #99. We expect to correct this in the 1.42 release.

You mean 1.43, or will you re-release a signed 1.42?
